name = "Portinari"
uuid = "72ee7ba2-92b2-4971-a97d-28f521fe8910"
authors = ["Guilherme Haetinger <ghaetinger@gmail.com>"]
version = "0.1.0"

[deps]
AbstractPlutoDingetjes = "6e696c72-6542-2067-7265-42206c756150"
Deno_jll = "04572ae6-984a-583e-9378-9577a1c2574d"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PlutoDevMacros = "a0499f29-c39b-4c5c-807c-88074221b949"
PlutoLinks = "0ff47ea0-7a50-410d-8455-4348d5de0420"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"

[compat]
julia = "1.6"
AbstractPlutoDingetjes = "0"
HypertextLiteral = "0"
Parameters = "0"
PlutoDevMacros = "0"
PlutoLinks = "0"
PlutoUI = "0"